# Generated by Django 4.2.4 on 2023-09-11 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suivi_projets', '0002_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='contributors',
            field=models.ManyToManyField(through='suivi_projets.Contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
