# Generated by Django 4.2.4 on 2023-09-10 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_projets', '0003_issue_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='projet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='suivi_projets.projet'),
            preserve_default=False,
        ),
    ]
